complete -c ticket -n '__fish_use_subcommand' -s h -l help -d 'Show help message and exit'
complete -c ticket -n '__fish_use_subcommand' -xa new -d 'Create a new ticket'
complete -c ticket -n '__fish_seen_subcommand_from new' -s s -l status -xa 'open closed' -d 'Ticket status'
complete -c ticket -n '__fish_seen_subcommand_from new' -s h -l help -d 'Show help message and exit'
complete -c ticket -n '__fish_use_subcommand' -xa edit -d 'Edit a ticket'
complete -c ticket -n '__fish_seen_subcommand_from edit' -s s -l status -xa 'open closed' -d 'Ticket status'
complete -c ticket -n '__fish_seen_subcommand_from edit' -s t -l title -r -d 'Ticket title'
complete -c ticket -n '__fish_seen_subcommand_from edit' -s h -l help -d 'Show help message and exit'
complete -c ticket -n '__fish_seen_subcommand_from edit' -xa '(ticket list -f "\$id"(string unescape "\t")"\$title")'
complete -c ticket -n '__fish_use_subcommand' -xa list -d 'list tickets'
complete -c ticket -n '__fish_seen_subcommand_from list' -s s -l status -xa 'open closed all' -d 'Ticket status'
complete -c ticket -n '__fish_seen_subcommand_from list' -s f -l format -r -d 'Output format in Python string.Template'
complete -c ticket -n '__fish_seen_subcommand_from list' -s h -l help -d 'Show help message and exit'
